version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AIzaSyDV171HM_eOSA_gZGHU8O41Z8ys63aShBo}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-KcQSASdHnTuTj9UHoLXaHufYbcyYnRXS}
      - RATELIMIT_USER_RPM=20
      - RATELIMIT_PROVIDER_RPM=60
    depends_on:
      - mongodb
      - chromadb
    volumes:
      - .:/app

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  chromadb:
    image: chromadb/chroma:0.5.1
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma

volumes:
  mongodb_data:
  chromadb_data:
